server:
  port: 8080

spring:
  main:
    banner-mode: off

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/javaquiz?currentSchema=e2etesting
    username: test
    password: 111